/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels.date_panel;

import javax.swing.JFrame;
import org.joda.time.LocalDate;

/**
 *
 * @author vatian
 */
public class DatePanel extends javax.swing.JPanel {

    public LocalDate startdate;
    public LocalDate enddate;
    /**
     * Creates new form DatePanel
     */
    public DatePanel() {
        
        
         
        initComponents();
        
        startdate = new LocalDate(2015,9,1);
        enddate   = new LocalDate(2016,8,31);
        start_day_spinner.setValue(startdate.getDayOfMonth());
        start_month_spinner.setValue(startdate.getMonthOfYear());
        start_year_spinner.setValue(startdate.getYear());
        end_day_spinner.setValue(enddate.getDayOfMonth());
        end_month_spinner.setValue(enddate.getMonthOfYear());
        end_year_spinner.setValue(enddate.getYear());
         
         
    }
    private void update_spinner(){
        
       start_day_spinner.setValue(startdate.getDayOfMonth());
       start_month_spinner.setValue(startdate.getMonthOfYear());
       start_year_spinner.setValue(startdate.getYear());
       end_day_spinner.setValue(enddate.getDayOfMonth());
       end_month_spinner.setValue(enddate.getMonthOfYear());
       end_year_spinner.setValue(enddate.getYear());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        start_month_spinner = new javax.swing.JSpinner();
        start_day_spinner = new javax.swing.JSpinner();
        start_year_spinner = new javax.swing.JSpinner();
        day_label = new javax.swing.JLabel();
        month_label = new javax.swing.JLabel();
        year_label = new javax.swing.JLabel();
        end_day_spinner = new javax.swing.JSpinner();
        end_month_spinner = new javax.swing.JSpinner();
        end_year_spinner = new javax.swing.JSpinner();
        start_label = new javax.swing.JLabel();
        end_label = new javax.swing.JLabel();

        start_month_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                start_month_spinnerStateChanged(evt);
            }
        });

        start_day_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                start_day_spinnerStateChanged(evt);
            }
        });

        start_year_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                start_year_spinnerStateChanged(evt);
            }
        });

        day_label.setText("Day");

        month_label.setText("Month");

        year_label.setText("Year");

        end_day_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                end_day_spinnerStateChanged(evt);
            }
        });

        end_year_spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                end_year_spinnerStateChanged(evt);
            }
        });

        start_label.setText("Starting :");

        end_label.setText("Ending:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(start_label)
                    .addComponent(end_label))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(day_label)
                        .addGap(65, 65, 65)
                        .addComponent(month_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(end_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end_month_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_month_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(year_label)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(end_year_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start_year_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day_label)
                    .addComponent(month_label)
                    .addComponent(year_label))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_month_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_year_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(end_day_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end_month_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end_year_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end_label))
                .addContainerGap(212, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void start_day_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {                                               
     int a=(int) start_day_spinner.getValue();
     int b= (int) startdate.getDayOfMonth();
     int c = a-b;
     startdate= startdate.plusDays(c);
     
    }                                              

    private void end_day_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {                                             
     int a=(int) end_day_spinner.getValue();
     int b= (int) enddate.getDayOfMonth();
     int c = a-b;
     enddate = enddate.plusDays(c);
     
    }                                            

    private void start_month_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {                                                 
     int a=(int) start_month_spinner.getValue();
     int b= (int) startdate.getMonthOfYear();
     int c = a-b;
    startdate=  startdate.plusMonths(c);
        
    }                                                

    private void start_year_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {                                                
     int a=(int) start_year_spinner.getValue();
     int b= (int) startdate.getYear();
     int c = a-b;
     startdate =startdate.plusYears(c);
    }                                               

    private void end_year_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {                                              
        int a=(int) end_year_spinner.getValue();
        int b=(int) enddate.getYear();
        int c = a-b;
        enddate= enddate.plusYears(c);
    }                                             
    private void end_month_spinnerStateChanged(javax.swing.event.ChangeEvent evt) {
        int a=(int) end_month_spinner.getValue();
        int b=(int) enddate.getMonthOfYear();
        int c = a-b;
        enddate= enddate.plusMonths(c);   
     } 

     public static void main(String args[]){
         JFrame frame=new JFrame();
         frame.add(new DatePanel());
         frame.setVisible(true);
         frame.setBounds(500,500,500, 500);
     }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel day_label;
    private javax.swing.JSpinner end_day_spinner;
    private javax.swing.JLabel end_label;
    private javax.swing.JSpinner end_month_spinner;
    private javax.swing.JSpinner end_year_spinner;
    private javax.swing.JLabel month_label;
    private javax.swing.JSpinner start_day_spinner;
    private javax.swing.JLabel start_label;
    private javax.swing.JSpinner start_month_spinner;
    private javax.swing.JSpinner start_year_spinner;
    private javax.swing.JLabel year_label;
    // End of variables declaration                   
}
