/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import dedheproject.dataclasses.Breaker;
import dedheproject.dataclasses.CachedData;
import dedheproject.dataclasses.PowerPlant;
import dedheproject.dataclasses.Transformer;

/**
 *
 * @author Paris
 */
public class ChoosingPanel extends javax.swing.JPanel {

    public PowerPlant chosen_plant;
    public Transformer chosen_transformer;
    public Breaker chosen_breaker;

    public ChoosingPanel() {
        initComponents();

        plant_combobox.removeAllItems();
        transformer_combobox.removeAllItems();
        breaker_combobox.removeAllItems();

        update_plants();
        chosen_plant = (PowerPlant) plant_combobox.getSelectedItem();

        update_transformers();
        chosen_transformer = (Transformer) transformer_combobox.getSelectedItem();

        update_breakers();
        chosen_breaker = (Breaker) breaker_combobox.getSelectedItem();

    }

    void update_plants() {
        plant_combobox.removeAllItems();

        for (PowerPlant b : CachedData.powerplants) {
            plant_combobox.addItem(b);
        }

    }

    void update_transformers() {

        transformer_combobox.removeAllItems();

        if (chosen_plant != null) {
            for (Transformer t : chosen_plant.transformers) {
                transformer_combobox.addItem(t);
            }
        }
    }

    void update_breakers() {
        breaker_combobox.removeAllItems();
        if (chosen_transformer != null) {
            for (Breaker b : chosen_transformer.breakers) {
                breaker_combobox.addItem(b);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breaker_combobox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        transformer_label = new javax.swing.JLabel();
        breaker_label = new javax.swing.JLabel();
        plant_combobox = new javax.swing.JComboBox();
        transformer_combobox = new javax.swing.JComboBox();

        breaker_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breaker_comboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Plant");

        transformer_label.setText("Transformer");

        breaker_label.setText("Breaker");

        plant_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant_comboboxActionPerformed(evt);
            }
        });

        transformer_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformer_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(plant_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transformer_label)
                    .addComponent(transformer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(breaker_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(breaker_label)
                        .addGap(30, 30, 30)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transformer_label)
                    .addComponent(jLabel1)
                    .addComponent(breaker_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plant_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transformer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breaker_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void breaker_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breaker_comboboxActionPerformed
        chosen_breaker = (Breaker) breaker_combobox.getSelectedItem();
    }//GEN-LAST:event_breaker_comboboxActionPerformed

    private void plant_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant_comboboxActionPerformed
        chosen_plant = (PowerPlant) plant_combobox.getSelectedItem();
        update_transformers();
        chosen_transformer = (Transformer) transformer_combobox.getSelectedItem();
        update_breakers();
        chosen_breaker = (Breaker) breaker_combobox.getSelectedItem();
    }//GEN-LAST:event_plant_comboboxActionPerformed

    private void transformer_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformer_comboboxActionPerformed
        chosen_transformer = (Transformer) transformer_combobox.getSelectedItem();
        update_breakers();
        chosen_breaker = (Breaker) breaker_combobox.getSelectedItem();

    }//GEN-LAST:event_transformer_comboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox breaker_combobox;
    private javax.swing.JLabel breaker_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox plant_combobox;
    private javax.swing.JComboBox transformer_combobox;
    private javax.swing.JLabel transformer_label;
    // End of variables declaration//GEN-END:variables
}
