/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import dedheproject.dataclasses.Breaker;
import dedheproject.dataclasses.CachedData;
import dedheproject.dataclasses.PowerPlant;
import dedheproject.dataclasses.Transformer;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Paris
 */
public final class ChoosingPanel extends javax.swing.JPanel {

    public PowerPlant selected_plant = null;
    public Transformer selected_transformer = null;
    public Breaker selected_breaker = null;

    public ChoosingPanel() {

        initComponents();
        setBounds(0,0,400,70);
        updateall();

    }

    void updateall() {

        update_plants();
        selected_plant = (PowerPlant) plant_combobox.getSelectedItem();

        update_transformers();
        selected_transformer = (Transformer) transformer_combobox.getSelectedItem();

        update_breakers();
        selected_breaker = (Breaker) breaker_combobox.getSelectedItem();
    }

    void update_plants() {
        DefaultComboBoxModel plantcombobox = new DefaultComboBoxModel();
        plant_combobox.setModel(plantcombobox);

        try {
            CachedData.mutex.acquire();
        } catch (InterruptedException ex) {
            System.err.println("crash at CachedData mutex");
        }
        if (CachedData.powerplants.size() > 0) {
            plantcombobox = new DefaultComboBoxModel(CachedData.powerplants);
            plant_combobox.setModel(plantcombobox);
            plant_combobox.setSelectedIndex(0);
        }
        CachedData.mutex.release();
    }

    void update_transformers() {
        DefaultComboBoxModel transformercombobox = new DefaultComboBoxModel();
        transformer_combobox.setModel(transformercombobox);
        if (selected_plant != null) {
            try {
                CachedData.mutex.acquire();
            } catch (InterruptedException ex) {
                System.err.println("crash at CachedData mutex");
            }
            if (selected_plant.transformers.size() > 0) {

                transformercombobox = new DefaultComboBoxModel(selected_plant.transformers);
                transformer_combobox.setModel(transformercombobox);
                transformer_combobox.setSelectedIndex(0);
            }
            CachedData.mutex.release();
        }

    }

    void update_breakers() {
        DefaultComboBoxModel breakercombobox = new DefaultComboBoxModel();
        breaker_combobox.setModel(breakercombobox);
        if (selected_transformer != null) {
            try {
                CachedData.mutex.acquire();
            } catch (InterruptedException ex) {
                System.err.println("crash at CachedData mutex");
            }
            if (selected_transformer.breakers.size() > 0) {

                breakercombobox = new DefaultComboBoxModel(selected_transformer.breakers);
                breaker_combobox.setModel(breakercombobox);
                breaker_combobox.setSelectedIndex(0);
            }
            CachedData.mutex.release();
        }
    }

    void plantchange() {
        selected_plant = (PowerPlant) plant_combobox.getSelectedItem();
        update_transformers();
        selected_transformer = (Transformer) transformer_combobox.getSelectedItem();
        update_breakers();
        selected_breaker = (Breaker) breaker_combobox.getSelectedItem();
    }

    void transformerchange() {
        selected_transformer = (Transformer) transformer_combobox.getSelectedItem();
        update_breakers();
        selected_breaker = (Breaker) breaker_combobox.getSelectedItem();

    }

    void breakerchange() {
        selected_breaker = (Breaker) breaker_combobox.getSelectedItem();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breaker_combobox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        transformer_label = new javax.swing.JLabel();
        breaker_label = new javax.swing.JLabel();
        plant_combobox = new javax.swing.JComboBox();
        transformer_combobox = new javax.swing.JComboBox();

        breaker_combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breaker_comboboxItemStateChanged(evt);
            }
        });
        breaker_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breaker_comboboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Plant");

        transformer_label.setText("Transformer");

        breaker_label.setText("Breaker");

        plant_combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plant_comboboxItemStateChanged(evt);
            }
        });
        plant_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant_comboboxActionPerformed(evt);
            }
        });

        transformer_combobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transformer_comboboxItemStateChanged(evt);
            }
        });
        transformer_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformer_comboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(plant_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transformer_label)
                    .addComponent(transformer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(breaker_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(breaker_label)
                        .addGap(30, 30, 30)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transformer_label, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(breaker_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plant_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transformer_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breaker_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void breaker_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breaker_comboboxActionPerformed

    }//GEN-LAST:event_breaker_comboboxActionPerformed

    private void plant_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant_comboboxActionPerformed


    }//GEN-LAST:event_plant_comboboxActionPerformed

    private void transformer_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformer_comboboxActionPerformed

    }//GEN-LAST:event_transformer_comboboxActionPerformed

    private void plant_comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plant_comboboxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            plantchange();
        }
    }//GEN-LAST:event_plant_comboboxItemStateChanged

    private void transformer_comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transformer_comboboxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            transformerchange();
        }
    }//GEN-LAST:event_transformer_comboboxItemStateChanged

    private void breaker_comboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breaker_comboboxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            breakerchange();
        }
    }//GEN-LAST:event_breaker_comboboxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox breaker_combobox;
    public javax.swing.JLabel breaker_label;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JComboBox plant_combobox;
    public javax.swing.JComboBox transformer_combobox;
    public javax.swing.JLabel transformer_label;
    // End of variables declaration//GEN-END:variables
}
