/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DB_data_loader.LoadDataFromDB;
import DB_data_loader.StaticCachedData;
import DB_data_loader.data_classes.Breaker;
import DB_data_loader.data_classes.ElectricalValue;
import DB_data_loader.data_classes.Transformer;
import java.util.Vector;
import org.joda.time.LocalDate;
import panels.plant_transformer_breaker_component.ChoosingPanel;

/**
 *
 * @author Paris
 */
public class TestDataLoading extends javax.swing.JFrame {

    /**
     * Creates new form testdataloading
     */
    ChoosingPanel choosingpanel;

    public TestDataLoading() {

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        initComponents();
        
        choosingpanel = new ChoosingPanel();
        add(choosingpanel);
        LocalDate startdate = new LocalDate(2015, 1, 14);
        LocalDate enddate = new LocalDate(2015, 1, 15);

        Breaker testbreaker = StaticCachedData.db_breakers.get(0);
        Transformer testtransformer = StaticCachedData.db_transformers.get(0);

        Vector<ElectricalValue> data1 = LoadDataFromDB.get_breaker_data(testbreaker, startdate, enddate);
        Vector<ElectricalValue> data2 = LoadDataFromDB.get_transformer_data(testtransformer, startdate, enddate);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
