/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports;

import DB_data_loader.data_classes.ElectricalValue;
import java.util.Vector;
import org.joda.time.DateTime;

/**
 *
 * @author vatian
 */
public class ReportPanel extends javax.swing.JPanel {

    private Vector<ElectricalValue> data1;
    public float avg, sum;
    public ElectricalValue max, min;

    /**
     * Creates new form max_panel
     */
    public ReportPanel(Vector<ElectricalValue> data_input) {
        data1 = data_input;
        initComponents();

        min_finder();
        min_textfield.setEditable(false);
        sum_finder();
        sum_textfield.setEditable(false);
        max_finder();
        max_textfield.setEditable(false);
        avg_finder();
        avg_textfield.setEditable(false);

        setSize(400, 400);
        setVisible(true);
    }

    /*  public ReportPanel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        max_textfield = new javax.swing.JTextField();
        min_textfield = new javax.swing.JTextField();
        avg_textfield = new javax.swing.JTextField();
        sum_textfield = new javax.swing.JTextField();
        max_label = new javax.swing.JLabel();
        min_label = new javax.swing.JLabel();
        avg_label = new javax.swing.JLabel();
        sum_label = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 105, -1, -1));
        add(max_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, -1));
        add(min_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 210, -1));
        add(avg_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 154, -1));
        add(sum_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 154, -1));

        max_label.setText("Maximum is :");
        add(max_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        min_label.setText("Minimum is :");
        add(min_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        avg_label.setText("Average is :");
        add(avg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        sum_label.setText("Sum is :");
        add(sum_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void max_finder() {
        if (data1.isEmpty()) {
            max_textfield.setText("No data man");
        } else {
            max = data1.get(0);
            for (int i = 1; i < data1.size(); i++) {

                ElectricalValue curr = data1.get(i);
                if (curr.value > max.value) {
                    max = curr;
                }
            }
            max_textfield.setText(" " + max.toString());
        }

    }

    public void min_finder() {
        if (data1.isEmpty()) {
            min_textfield.setText("No data");

        } else {
            min = data1.get(0);
            for (int i = 1; i < data1.size(); i++) {
                ElectricalValue curr = data1.get(i);
                if (curr.value < min.value) {
                    min = curr;
                }
            }
            min_textfield.setText(" " + min.toString());

        }

    }

    public void avg_finder() {
        if (data1.isEmpty()) {
            avg_textfield.setText("No data");

        } else {
            float avg = data1.get(0).value;
            for (int i = 1; i < data1.size(); i++) {
                avg = (avg + data1.get(i).value);

            }
            avg = (avg / data1.size());

            int avg1 = Math.round(avg * 100);
            float avg2 = avg1 / 100f;

            avg_textfield.setText(" " + avg2);
        }

    }

    public void sum_finder() {
        if (data1.isEmpty()) {
            sum_textfield.setText("No data");

        } else {

            float sum = data1.get(0).value;
            for (int i = 1; i < data1.size(); i++) {
                sum = (sum + data1.get(i).value);

            }
            int sum1 = Math.round(sum * 100);
            float sum2 = sum1 / 100f;
            sum_textfield.setText(" " + sum2);
        }

    }

    public static void main(String args[]) {
        Vector<ElectricalValue> v = new Vector<ElectricalValue>();
        v.add(new ElectricalValue(new DateTime(), 17.5f));
        v.add(new ElectricalValue(new DateTime(), 18.5f));
        v.add(new ElectricalValue(new DateTime(), 19.5f));
        v.add(new ElectricalValue(new DateTime(), 17.0f));
        v.add(new ElectricalValue(new DateTime(), 17.0f));

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /* JFrame frame = new JFrame();
                frame.add(new ReportPanel(v));
                frame.setVisible(true);
                frame.setSize(400, 250);*/
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avg_label;
    private javax.swing.JTextField avg_textfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel max_label;
    private javax.swing.JTextField max_textfield;
    private javax.swing.JLabel min_label;
    private javax.swing.JTextField min_textfield;
    private javax.swing.JLabel sum_label;
    private javax.swing.JTextField sum_textfield;
    // End of variables declaration//GEN-END:variables
}
